export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_ERRORS = 'SET_USER_ERRORS';
export const SET_USER_CONTENT = 'SET_USER_CONTENT';
export const DELETE_CONTENT = 'DELETE_CONTENT';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const ADD_CONTENT = 'ADD_CONTENT';