export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_CONTENT = 'SET_USER_CONTENT';
export const DELETE_CONTENT = 'DELETE_CONTENT';
export const ADD_CONTENT = 'ADD_CONTENT';
export const CONTENT_SUCCESS = 'CONTENT_SUCCESS';
